### PR TITLE
Account for nic.nrw fee-0.6 usage

### PR DESCRIPTION
**Pull request by cee-dub**

### CODE REVIEW

**Comment by ydnar** [comment]
@cee-dub should we still merge this?

**Comment by cee-dub** [comment]
No idea. Wish there was a linked issue or other detail about why this change was needed.

**Comment by case** [comment]
domainr/mustang#258 is linked above. I'll test and update with what I find.

**Comment by cee-dub** [comment]
Then I'd say definitely not, this is much older than that one and want kept up to date as things evolved

**Comment by cee-dub** [comment]
Wasn't*

**Comment by case** [comment]
Yep this isn't relevant anymore.

**Pull request closed without merging**
